defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  database: skag_server_rails_development
  <<: *defaults

test:
  database: skag_server_rails_test
  <<: *defaults

production:
  database: skag_server_rails_production
  <<: *defaults

